queue_rules:
  - name: default
    merge_conditions: []

merge_protections:
  - name: source changes need a review
    if:
      - files~=^src/
    success_conditions:
      - "#approved-reviews-by>=1"
